### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: E("un support database type for:\"VARCHAR\"!")',

### ISSUE THREAD

**Issue by insanebaba** [rbatis/rbatis#22]
unable to parse varchar to string 

database: postgres 12.

query : select name from <table_name>;

**Comment by insanebaba** [comment]
I see this error is coming, due to missing **VARCHAR** mapping in file [postgres/value.rs](https://github.com/rbatis/rbatis/blob/master/rbatis-core/src/postgres/value.rs)

Can you please update it?

**Comment by insanebaba** [comment]
Also can you add geometric Point type ? 👍

**Comment by zhuxiujia** [comment]
I have completed this type, which has not been released yet, but you can try the version on Github


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rbatis/rbatis"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月22日(星期二) 晚上9:57
收件人:&nbsp;"rbatis/rbatis"<rbatis@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [rbatis/rbatis] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: E("un support database type for:\"VARCHAR\"!")', (#22)





 
Also can you add geometric Point type ? 👍

**Comment by insanebaba** [comment]
> I have completed this type, which has not been released yet, but you can try the version on Github
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "rbatis/rbatis" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月22日(星期二) 晚上9:57 收件人:&nbsp;"rbatis/rbatis"<rbatis@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [rbatis/rbatis] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: E("un support database type for:\"VARCHAR\"!")', (#22) Also can you add geometric Point type ? 👍 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you, I tried and it works, though **Point** type is still missing, just a headsup

**Comment by zhuxiujia** [comment]
postgresql support not&nbsp;perfect
if you have&nbsp; better solution, welcome to commit code merge




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rbatis/rbatis"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月22日(星期二) 晚上11:06
收件人:&nbsp;"rbatis/rbatis"<rbatis@noreply.github.com&gt;;
抄送:&nbsp;"朱秀杰"<zhuxiujia@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [rbatis/rbatis] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: E("un support database type for:\"VARCHAR\"!")', (#22)





  
I have completed this type, which has not been released yet, but you can try the version on Github
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "rbatis/rbatis" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月22日(星期二) 晚上9:57 收件人:&nbsp;"rbatis/rbatis"<rbatis@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [rbatis/rbatis] thread 'main' panicked at 'called Result::unwrap() on an Err value: E("un support database type for:"VARCHAR"!")', (#22) Also can you add geometric Point type ? 👍 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
Thank you, I tried and it works, though Point type is still missing, just a headsup

**Comment by insanebaba** [comment]
> postgresql support not&nbsp;perfect if you have&nbsp; better solution, welcome to commit code merge
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "rbatis/rbatis" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月22日(星期二) 晚上11:06 收件人:&nbsp;"rbatis/rbatis"<rbatis@noreply.github.com&gt;; 抄送:&nbsp;"朱秀杰"<zhuxiujia@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [rbatis/rbatis] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: E("un support database type for:\"VARCHAR\"!")', (#22) I have completed this type, which has not been released yet, but you can try the version on Github … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "rbatis/rbatis" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月22日(星期二) 晚上9:57 收件人:&nbsp;"rbatis/rbatis"<rbatis@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [rbatis/rbatis] thread 'main' panicked at 'called Result::unwrap() on an Err value: E("un support database type for:"VARCHAR"!")', (#22) Also can you add geometric Point type ?  — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Thank you, I tried and it works, though Point type is still missing, just a headsup — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

I tried writing code for point, but Rust is a pain to work with. I spent all day trying to add **geo_types** in rbatis-core but to no luck. I'm sorry that I cannot help, I want to and I have 10 years of programming experience but rust is still pain. I try migrating my api next year if geotypes are integrated. You can also take a look at https://github.com/quek/arysn as He's also trying to improve ORM space in rust. My apologies  that I cannot contribute.
